#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Monitors
#bspc monitor HDMI-1 -d 7 8 9

# Set Wallpaper
feh --bg-fill ~/Pictures/white-tree.jpg

# Start Polybar
bash ~/.config/polybar/launch.sh
#polybar example

# Start Compositor
compton -b --config ~/.config/compton/compton.conf

# Start Spotifyd daemon
#spotifyd
